[project]
name = "ppx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax>=0.10.3",
    "jax-tqdm>=0.3.1",
    "jax>=0.5.0",
    "distrax>=0.1.5",
]
